name: Update Rule

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Rule Providers
        working-directory: ./rule_provider
        run: |
          echo "Downloading oisd full source list..."
          curl -s https://dblw.oisd.nl/ -o ads.yaml
          sed -i '/^$/d' ads.yaml
          sed -i '4,9d' ads.yaml
          sed -ie '/^#/! s/*./- "+./' ads.yaml
          sed -ie '/^#/! s/$/"/' ads.yaml
          sed -i 's|# Title: oisd big|payload:|' ads.yaml
          rm -f ads.yamle
          
          echo "Downloading banking source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/banking.yaml -o banking.yaml
          rm -f banking.yamle
          
          echo "Downloading Discord source list..."
          curl -s https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Discord/Discord.yaml -o discord.yaml
          rm -f discord.yamle
          
          echo "Downloading gaming source list..."
          curl -s https://rules.kr328.app/category-games.yaml -o gaming.yaml
          rm -f gaming.yamle
          
          echo "Downloading judi source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/judi.yaml -o judi.yaml
          rm -f judi.yamle
          
          echo "Downloading olshop source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/olshop.yaml -o olshop.yaml
          rm -f olshop.yamle
          
          echo "Downloading porn source list..."
          curl -s https://rules.kr328.app/category-porn.yaml -o saru.yaml
          rm -f saru.yamle
          
          echo "Downloading sosmed source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/sosmed.yaml -o sosmed.yaml
          rm -f sosmed.yamle
          
          echo "Downloading stream source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/stream.yaml -o stream.yaml
          rm -f stream.yamle
          
          echo "Downloading telecidr source list..."
          curl -s https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt -o telecidr.yaml
          rm -f telecidr.yamle
          
          echo "Downloading telegram source list..."
          curl -s https://rules.kr328.app/telegram.yaml -o telegram.yaml
          rm -f telegram.yamle
          
          echo "Downloading Disney+ source list..."
          curl -s https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney.yaml -o disney.yaml
          rm -f disney.yamle
          
          echo "Downloading Line source list..."
          curl -s https://rules.kr328.app/line.yaml -o line.yaml
          rm -f line.yamle
          
          echo "Downloading Netflix source list..."
          curl -s https://rules.kr328.app/netflix.yaml -o netflix.yaml
          rm -f netflix.yamle
          
          echo "Downloading PrimeVideo source list..."
          curl -s https://rules.kr328.app/primevideo.yaml -o primevideo.yaml
          rm -f primevideo.yamle
          
          echo "Downloading TikTok source list..."
          curl -s https://rules.kr328.app/tiktok.yaml -o tiktok.yaml
          rm -f tiktok.yamle
          
          echo "Downloading Twitter source list..."
          curl -s https://rules.kr328.app/twitter.yaml -o twitter.yaml
          rm -f twitter.yamle
          
          echo "Downloading YouTube source list..."
          curl -s https://rules.kr328.app/youtube.yaml -o youtube.yaml
          rm -f youtube.yamle
          
          echo "Downloading Zerotier source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/zerotier.yaml -o zerotier.yaml
          rm -f zerotier.yamle
          
      - name: Trigger Bot Update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: https://github.com/fyn170/open_clash
          event-type: update-rule

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Rule Provider
