name: Update Rule

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Rule Providers
        working-directory: ./rule_provider
        run: |
          echo "Downloading oisd full source list..."
          curl -s https://dblw.oisd.nl/ -o ads.yaml
          sed -i '/^$/d' ads.yaml
          sed -i '4,9d' ads.yaml
          #start word
          sed -ie '/^#/! s/*./- "+./' ads.yaml
          #end word
          sed -ie '/^#/! s/$/"/' ads.yaml
          sed -i 's|# Title: oisd big|payload:|' ads.yaml
          rm -fr ads.yamle
          
          # Banking
          echo "Downloading Discord source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/banking.yaml -o banking.yaml
          rm -fr banking.yamle
          
	  # Discord
          echo "Downloading Discord source list..."
          curl -s https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Discord/Discord.yaml -o discord.yaml
          rm -fr discord.yamle
          
          # Gaming
          echo "Downloading rule_games source list..."
          curl -s https://rules.kr328.app/category-games.yaml -o gaming.yaml
          rm -fr gaming.yamle
		  
          # Judi
          echo "Downloading Discord source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/judi.yaml -o judi.yaml
          rm -fr judi.yamle
		  
          # Olshop
          echo "Downloading Discord source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/olshop.yaml -o olshop.yaml
          rm -fr olshop.yamle
		  
          # Porn
          echo "Downloading rule_porn source list..."
          curl -s https://rules.kr328.app/category-porn.yaml -o saru.yaml
          rm -fr saru.yamle
          
          # Sosmed
          echo "Downloading Discord source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/sosmed.yaml -o sosmed.yaml
          rm -fr sosmed.yamle
		  
          # Stream
          echo "Downloading Discord source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/stream.yaml -o stream.yaml
          rm -fr stream.yamle
		  
          # Telegram
          echo "Downloading rule_telegramcidr source list..."
          curl -s https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt -o telecidr.yaml
          rm -fr telecidr.yamle
          echo "Downloading rule_telegram source list..."
          curl -s https://rules.kr328.app/telegram.yaml -o telegram.yaml
          rm -fr telegram.yamle
          
          # Disney+
          echo "Downloading rule_disneyplus source list..."
          curl -s https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney.yaml -o disney.yaml
          rm -fr disney.yamle
          
          # Line
          echo "Downloading rule_line source list..."
          curl -s https://rules.kr328.app/line.yaml -o line.yaml
          rm -fr line.yamle
          
          # Netflix
          echo "Downloading rule_netflix source list..."
          curl -s https://rules.kr328.app/netflix.yaml -o netflix.yaml
          rm -fr netflix.yamle
          
          # PrimeVideo
          echo "Downloading rule_primevideo source list..."
          curl -s https://rules.kr328.app/primevideo.yaml -o primevideo.yaml
          rm -fr primevideo.yamle
          
          # Tiktok
          echo "Downloading rule_tiktok source list..."
          curl -s https://rules.kr328.app/tiktok.yaml -o tiktok.yaml
          rm -fr tiktok.yamle
          
          # Twitter
          echo "Downloading rule_twitter source list..."
          curl -s https://rules.kr328.app/twitter.yaml -o twitter.yaml
          rm -fr twitter.yamle
          
          # Youtube
          echo "Downloading rule_youtube source list..."
          curl -s https://rules.kr328.app/youtube.yaml -o youtube.yaml
          rm -fr youtube.yamle
		  
          # Zerotier
          echo "Downloading Discord source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/zerotier.yaml -o zerotier.yaml
          rm -fr zerotier.yamle
		  
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Rule Provider
