name: Update Rule

on:
  schedule:
    - cron: '0 17 * * *'    # Auto update rule 00.00 WIB (GMT+7)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Rule Providers
        working-directory: ./rule_provider
        run: |
          echo "Downloading oisd full source list..."
          curl -s https://big.oisd.nl/ -o ads.txt
          sed -i '1d' ads.txt
          sed -i 's/^\!/#/g' ads.txt
          sed -i '4,7d' ads.txt
          sed -i 's/||/  - "+./g' ads.txt
          sed -i -e '$a"' ads.txt
          sed -i 's|# Title: oisd big|payload:|' ads.txt
          sed -i '/^$/d' ads.txt
          sed -i 's/\^/"/g' ads.txt
          sed -i '$d' ads.txt
          mv ads.txt ads.yaml

          echo "Downloading Apkpure source list..."
          curl -s https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apkpure/Apkpure.yaml -o apkpure.yaml
          
          echo "Downloading banking source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/banking.yaml -o banking.yaml

          echo "Downloading Cloudflare source list..."
          curl -s https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloudflare/Cloudflare.yaml -o cloudflare.yaml
          
          echo "Downloading Discord source list..."
          curl -s https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Discord/Discord.yaml -o discord.yaml

          echo "Downloading gaming source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/gaming.yaml -o gaming.yaml

          echo "Downloading Garena source list..."
          curl -s https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Garena/Garena.yaml -o garena.yaml
          
          echo "Downloading IpTvOther source list..."
          curl -s https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/IPTVOther/IPTVOther_Classical.yaml -o iptv.yaml
          
          echo "Downloading Instagram source list..."
          curl -s https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.yaml -o instagram.yaml
          
          echo "Downloading judi source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/judi.yaml -o judi.yaml

          echo "Downloading olshop source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/olshop.yaml -o olshop.yaml

          echo "Downloading porn source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/saru.yaml -o saru.yaml

          echo "Downloading sosmed source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/sosmed.yaml -o sosmed.yaml

          echo "Downloading stream source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/stream.yaml -o stream.yaml

          echo "Downloading telecidr source list..."
          curl -s https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt -o telecidr.yaml

          echo "Downloading telegram source list..."
          curl -s https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml -o telegram.yaml

          echo "Downloading Disney+ source list..."
          curl -s https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney.yaml -o disney.yaml

          echo "Downloading Line source list..."
          curl -s https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Line/Line.yaml -o line.yaml

          echo "Downloading Netflix source list..."
          curl -s https://cdn.jsdelivr.net/gh/DustinWin/clash-ruleset@release/netflix.yaml -o netflix.yaml

          echo "Downloading PrimeVideo source list..."
          curl -s https://cdn.jsdelivr.net/gh/DustinWin/clash-ruleset@release/primevideo.yaml -o primevideo.yaml

          echo "Downloading TikTok source list..."
          curl -s https://cdn.jsdelivr.net/gh/DustinWin/clash-ruleset@release/tiktok.yaml -o tiktok.yaml

          echo "Downloading Twitter source list..."
          curl -s https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml -o twitter.yaml

          echo "Downloading YouTube source list..."
          curl -s https://cdn.jsdelivr.net/gh/DustinWin/clash-ruleset@release/youtube.yaml -o youtube.yaml

          echo "Downloading Zerotier source list..."
          curl -s https://raw.githubusercontent.com/fyn170/conf-cfm/main/confs/rule/zerotier.yaml -o zerotier.yaml

      - name: Trigger Bot Update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: fyn170/open_clash
          event-type: update-rule

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto Update
